### ISSUE TITLE
[Proposal] Add option to skip tool name availability check

### ISSUE THREAD

**Issue by t-karcher** [lucaswerkmeister/cookiecutter-toolforge#1]
Great template! I successfully used it for a new tool, but it would be nice to add an option for using it for old / abandoned tools as well, to give them a fresh and clean (re)start! Currently, entering an existing tool name fails due to the mandatory availability check.

**Comment by lucaswerkmeister** [comment]
Hm, good idea – that should also help if the API has a hiccup ([as happened with SpeedPatrolling](https://lucaswerkmeister.de/posts/2019/01/04/speedpatrolling/)).
